
export const allRecipes: { [key: string]: any } = {
  'moqueca-de-banana-da-terra': {
    title: "Moqueca de Banana-da-Terra",
    author: "Ana G.",
    difficulty: "Médio",
    description: "Essa receita tem um lugar especial no meu coração. É a minha versão vegana da moqueca que minha avó baiana fazia. O cheiro do azeite de dendê e do leite de coco cozinhando me transporta direto para a cozinha dela. É um prato que abraça, perfeito para um almoço de domingo em família ou para aquecer a alma num dia chuvoso. Espero que vocês sintam o mesmo carinho que eu coloco em cada panela!",
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    category: "Zero Lactose",
    tags: ["Vegano", "Sem Glúten", "Prato Principal"],
    ingredients: [
        { value: "2 colheres de sopa de azeite de oliva" },
        { value: "1 cebola grande, picada" },
        { value: "1 pimentão vermelho, sem sementes, em tiras" },
        { value: "1 pimentão amarelo, sem sementes, em tiras" },
        { value: "3 dentes de alho, picados" },
        { value: "1 pimenta dedo-de-moça, sem sementes, picadinha (opcional)" },
        { value: "2 tomates maduros, sem pele e sementes, picados" },
        { value: "4 bananas-da-terra não muito maduras, em rodelas grossas" },
        { value: "400ml de leite de coco (de garrafinha, se possível)" },
        { value: "2 colheres de sopa de azeite de dendê" },
        { value: "1/2 xícara de coentro fresco picado" },
        { value: "1/2 xícara de cebolinha fresca picada" },
        { value: "Sal e pimenta do reino a gosto" },
    ],
    instructions: [
        { value: "Em uma panela de barro ou uma panela grande e funda, aqueça o azeite de oliva em fogo médio. Refogue a cebola e o alho até ficarem translúcidos e perfumados." },
        { value: "Adicione os pimentões e a pimenta dedo-de-moça (se estiver usando). Cozinhe por cerca de 5 minutos, até que comecem a amaciar." },
        { value: "Acrescente os tomates picados e refogue por mais alguns minutos, até que comecem a desmanchar e formar um molho." },
        { value: "Com cuidado, arrume as rodelas de banana-da-terra sobre o refogado, formando uma camada única. Tempere com sal e pimenta do reino." },
        { value: "Despeje o leite de coco sobre as bananas, garantindo que todas fiquem submersas. Reduza o fogo para o mínimo, tampe a panela e cozinhe por cerca de 15 a 20 minutos, ou até que as bananas estejam bem macias, mas sem desmanchar." },
        { value: "Nos últimos 5 minutos, regue com o azeite de dendê, misturando delicadamente para incorporar a cor e o sabor. Tenha cuidado para não quebrar as bananas." },
        { value: "Desligue o fogo, salpique o coentro e a cebolinha por cima. Sirva imediatamente, bem quentinho." },
    ],
    substitutions: [
        "**Banana-da-terra:** Se não encontrar, você pode usar palmito pupunha em rodelas. O sabor muda, mas a textura fica incrível!",
        "**Azeite de dendê:** É o coração da moqueca, mas se você não gostar ou não encontrar, pode omitir ou usar uma colher de chá de colorau para dar cor.",
        "**Coentro:** Eu amo, mas sei que é polêmico! Pode substituir por salsinha, sem problemas.",
    ],
    chefTip: "O segredo para uma banana-da-terra perfeita na moqueca é o ponto de maturação. Escolha bananas que estejam firmes, com a casca amarela e algumas manchas pretas, mas não completamente preta. Se estiver muito verde, ficará dura; se estiver muito madura, vai desmanchar e deixar o caldo doce demais. O equilíbrio é a chave!",
  },
  'bolo-de-cenoura-fofinho': {
    title: "Bolo de Cenoura Fofinho",
    author: "Mariana S.",
    difficulty: "Fácil",
    description: "Quem disse que bolo de cenoura precisa de leite? Essa receita é a prova de que é possível ter um bolo super fofinho, molhadinho e com uma cobertura de chocolate cremosa sem usar nenhum laticínio. É a receita que faço para todos os aniversários aqui em casa e ninguém nunca diz que é 'diferente'. É simplesmente... o melhor bolo de cenoura!",
    prepTime: 20,
    cookTime: 40,
    servings: 8,
    category: "Sobremesa",
    tags: ["Zero Lactose", "Sobremesa", "Bolo"],
    ingredients: [
        { value: "Massa:" },
        { value: "3 cenouras médias, descascadas e picadas" },
        { value: "3 ovos" },
        { value: "1 xícara de óleo vegetal (girassol, canola)" },
        { value: "2 xícaras de açúcar" },
        { value: "2 xícaras de farinha de trigo" },
        { value: "1 colher de sopa de fermento em pó" },
        { value: "Cobertura:" },
        { value: "1 xícara de bebida vegetal (aveia ou amêndoas)" },
        { value: "4 colheres de sopa de chocolate em pó (50% cacau)" },
        { value: "2 colheres de sopa de açúcar" },
        { value: "1 colher de sopa de margarina vegetal sem leite" },
    ],
    instructions: [
        { value: "Pré-aqueça o forno a 180°C. Unte e enfarinhe uma forma de buraco no meio." },
        { value: "No liquidificador, bata as cenouras, os ovos e o óleo até obter uma mistura homogênea e cremosa." },
        { value: "Em uma tigela grande, misture a farinha e o açúcar. Despeje a mistura do liquidificador sobre os secos e mexa bem com um fouet ou espátula até incorporar. Não bata demais." },
        { value: "Adicione o fermento em pó e misture delicadamente." },
        { value: "Despeje a massa na forma preparada e leve ao forno por cerca de 35-40 minutos, ou até que, ao espetar um palito, ele saia limpo." },
        { value: "Enquanto o bolo assa, prepare a cobertura. Em uma panela, misture a bebida vegetal, o chocolate em pó, o açúcar e a margarina." },
        { value: "Leve ao fogo médio, mexendo sempre, até a calda engrossar um pouco (cerca de 5-8 minutos). Ela vai encorpar mais depois de fria." },
        { value: "Desenforme o bolo ainda morno e despeje a cobertura quente por cima. Deixe esfriar antes de servir." },
    ],
    substitutions: [
        "**Ovos:** Para uma versão vegana, substitua os 3 ovos por 3 'ovos de linhaça' (3 colheres de sopa de farinha de linhaça + 9 colheres de sopa de água, deixar descansar 10 min).",
        "**Farinha de Trigo:** Pode usar uma mistura de farinha sem glúten na mesma proporção, mas a textura pode mudar um pouco.",
        "**Açúcar:** Pode ser substituído por açúcar demerara ou mascavo, o que deixará o bolo um pouco mais escuro e úmido.",
    ],
    chefTip: "O grande segredo para um bolo de cenoura fofinho é não bater a farinha no liquidificador. A farinha deve ser incorporada à mão, delicadamente. Isso evita que o glúten se desenvolva em excesso, o que deixaria o bolo pesado e 'borrachudo'. Mexa apenas o suficiente para a massa ficar homogênea!",
  },
  'pao-de-queijo-vegano': {
    title: "Pão de Queijo Vegano",
    author: "Carlos L.",
    difficulty: "Fácil",
    description: "Sempre fui louco por pão de queijo, e quando descobri a intolerância à lactose, achei que nunca mais comeria. Depois de muitos testes, cheguei a essa receita que, para mim, é perfeita! A batata entra para dar a maciez e a 'puxa-puxa' que o queijo daria, e o polvilho faz toda a mágica do sabor. É ótimo para o café da tarde ou para receber amigos.",
    prepTime: 20,
    cookTime: 20,
    servings: 16,
    category: "Lanche",
    tags: ["Sem Glúten", "Vegano", "Lanche"],
    ingredients: [
        { value: "2 xícaras de polvilho doce" },
        { value: "1 xícara de polvilho azedo" },
        { value: "1/2 xícara de óleo vegetal" },
        { value: "1 xícara de água fervente" },
        { value: "1 e 1/2 xícara de batata cozida e amassada (tipo purê)" },
        { value: "1/2 xícara de levedura nutricional (para sabor de queijo, opcional)" },
        { value: "1 colher de chá de sal (ou a gosto)" },
    ],
    instructions: [
        { value: "Cozinhe as batatas em água até ficarem bem macias. Escorra e amasse bem, como um purê. Reserve." },
        { value: "Em uma tigela grande, misture os dois tipos de polvilho e o sal." },
        { value: "Em uma panela, aqueça o óleo e a água até levantar fervura. Despeje essa mistura quente sobre os polvilhos e mexa rapidamente com uma colher. Isso vai 'escaldar' o polvilho, o que é crucial para a textura." },
        { value: "A massa ficará um pouco empelotada. Deixe amornar por uns 10 minutos." },
        { value: "Adicione a batata amassada e a levedura nutricional (se usar) à massa morna." },
        { value: "Agora, com as mãos, sove a massa até que todos os ingredientes estejam bem incorporados e ela fique lisa e homogênea. Se estiver muito grudenta, adicione um pouco mais de polvilho doce." },
        { value: "Pré-aqueça o forno a 200°C. Faça bolinhas com a massa e distribua em uma assadeira (não precisa untar)." },
        { value: "Asse por cerca de 20-25 minutos, ou até que estejam douradinhos por fora e macios por dentro." },
    ],
    substitutions: [
        "**Batata:** Batata baroa (mandioquinha) fica incrível e deixa o pão de queijo mais amarelinho e saboroso.",
        "**Levedura Nutricional:** Se não tiver, o pão de queijo ainda fica delicioso, mas com um sabor mais suave. Você pode adicionar temperos como alho em pó ou orégano à massa.",
    ],
    chefTip: "O pulo do gato é escaldar o polvilho com a mistura de água e óleo bem quente. Isso pré-cozinha o amido e garante que o pão de queijo cresça, fique aerado por dentro e com aquela casquinha crocante por fora. Não pule essa etapa!",
  },
  'mousse-de-chocolate-com-abacate': {
    title: "Mousse de Chocolate com Abacate",
    author: "Juliana P.",
    difficulty: "Fácil",
    description: "Essa é minha receita 'coringa' para jantares! Uma sobremesa super cremosa, intensa e deliciosa que ninguém acredita quando eu conto o ingrediente secreto: abacate! Ele dá a cremosidade perfeita sem deixar nenhum sabor residual. É saudável, fácil de fazer e agrada a todos, até as crianças. Prepare-se para os elogios!",
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    category: "Sobremesa",
    tags: ["Vegano", "Sem Glúten", "Sobremesa Rápida"],
    ingredients: [
        { value: "1 abacate grande e maduro (ou 2 pequenos)" },
        { value: "1/2 xícara de cacau em pó 100%" },
        { value: "1/2 xícara de melado de cana ou agave (ou a gosto)" },
        { value: "1/4 xícara de bebida vegetal (amêndoas, coco)" },
        { value: "1 colher de chá de extrato de baunilha" },
        { value: "1 pitada de sal" },
    ],
    instructions: [
        { value: "Corte o abacate ao meio, remova o caroço e retire toda a polpa com uma colher." },
        { value: "Coloque a polpa do abacate, o cacau em pó, o melado, a bebida vegetal, a baunilha e o sal em um processador de alimentos ou liquidificador potente." },
        { value: "Bata em velocidade alta por cerca de 2-3 minutos, parando para raspar as laterais se necessário, até a mistura ficar completamente lisa, cremosa e sem nenhum pedacinho de abacate." },
        { value: "Prove e ajuste a doçura se necessário, adicionando mais melado a gosto." },
        { value: "Divida a mousse em 4 potinhos ou taças." },
        { value: "Leve à geladeira por pelo menos 30 minutos para firmar um pouco mais. Sirva gelado." },
    ],
    substitutions: [
        "**Abacate:** Use abacates do tipo 'avocado' (o menor e de casca escura), pois eles são mais cremosos e têm sabor mais neutro.",
        "**Melado/Agave:** Pode ser substituído por tâmaras sem caroço (cerca de 6-8, hidratadas em água morna por 10 min) para um adoçante mais natural. Nesse caso, adicione as tâmaras junto com os outros ingredientes no processador.",
        "**Para um toque especial:** Adicione uma colher de sopa de pasta de amendoim ou 1/2 colher de chá de canela em pó à mistura.",
    ],
    chefTip: "A chave para uma mousse perfeita é a maturação do abacate. Ele precisa estar maduro e macio ao toque, mas sem partes escuras ou fibrosas. Um abacate 'passado' pode deixar um gosto amargo. Se o seu abacate estiver perfeito, o sabor dele some completamente, deixando só a cremosidade e o brilho do chocolate.",
  },
'estrogonofe-de-grao-de-bico': {
    title: "Estrogonofe de Grão-de-Bico",
    author: "Chef Léo",
    difficulty: "Fácil",
    description: "Uma releitura vegana e saudável do clássico estrogonofe. O grão-de-bico traz uma textura surpreendente e o molho, à base de castanha de caju, fica incrivelmente cremoso. É comfort food da melhor qualidade!",
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    category: "Zero Lactose",
    tags: ["Vegano", "Prato Principal", "Sem Glúten"],
    ingredients: [
        { value: "1 xícara de castanha de caju crua, demolhada por 4h" },
        { value: "1 e 1/2 xícara de água" },
        { value: "2 colheres de sopa de azeite" },
        { value: "1 cebola picada" },
        { value: "2 dentes de alho picados" },
        { value: "2 xícaras de cogumelos paris fatiados" },
        { value: "3 xícaras de grão-de-bico cozido" },
        { value: "3 colheres de sopa de extrato de tomate" },
        { value: "2 colheres de sopa de mostarda dijon" },
        { value: "1 colher de sopa de molho inglês vegano" },
        { value: "Sal e pimenta do reino a gosto" },
        { value: "Batata palha para servir" },
    ],
    instructions: [
        { value: "Escorra as castanhas de caju e bata no liquidificador com a água até obter um creme liso. Reserve." },
        { value: "Em uma panela, aqueça o azeite e refogue a cebola e o alho." },
        { value: "Adicione os cogumelos e cozinhe até dourarem." },
        { value: "Junte o grão-de-bico, extrato de tomate, mostarda e molho inglês. Misture bem." },
        { value: "Despeje o creme de castanha na panela, tempere com sal e pimenta e cozinhe em fogo baixo, sem deixar ferver, por cerca de 5 minutos, até o molho engrossar." },
        { value: "Sirva imediatamente com arroz branco e batata palha." },
    ],
    substitutions: [
        "**Grão-de-bico:** Pode ser substituído por palmito pupunha picado ou frango vegetal em cubos.",
        "**Cogumelos:** Use qualquer tipo de cogumelo fresco de sua preferência.",
    ],
    chefTip: "Não deixe o molho de castanhas ferver vigorosamente, pois ele pode talhar. O ideal é cozinhar em fogo bem baixo, mexendo sempre, apenas para aquecer e incorporar os sabores.",
  },
'risoto-de-abobora-com-salvia': {
    title: "Risoto de Abóbora com Sálvia Crocante",
    author: "Isabela M.",
    difficulty: "Médio",
    description: "Este risoto é a cara do outono! A doçura da abóbora combina perfeitamente com o sabor terroso da sálvia frita. A cremosidade vem do próprio amido do arroz, sem precisar de queijo ou manteiga.",
    prepTime: 10,
    cookTime: 30,
    servings: 3,
    category: "Zero Lactose",
    tags: ["Sem Glúten", "Vegano", "Prato Principal"],
    ingredients: [
        { value: "3 colheres de sopa de azeite" },
        { value: "1/2 cebola picada" },
        { value: "1 e 1/2 xícara de arroz arbóreo" },
        { value: "1/2 xícara de vinho branco seco" },
        { value: "2 xícaras de purê de abóbora cabotiá cozida" },
        { value: "4 xícaras de caldo de legumes quente" },
        { value: "10 folhas de sálvia fresca" },
        { value: "2 colheres de sopa de levedura nutricional (opcional)" },
        { value: "Sal e pimenta do reino a gosto" },
    ],
    instructions: [
        { value: "Em uma panela, aqueça 1 colher de sopa de azeite e frite as folhas de sálvia até ficarem crocantes. Retire e reserve em papel toalha." },
        { value: "Na mesma panela, adicione o restante do azeite e refogue a cebola." },
        { value: "Acrescente o arroz e frite por 1 minuto. Adicione o vinho e mexa até evaporar." },
        { value: "Adicione o purê de abóbora e uma concha do caldo de legumes quente. Mexa até o líquido ser absorvido." },
        { value: "Continue adicionando o caldo, concha por concha, mexendo sempre, até o arroz estar al dente." },
        { value: "Desligue o fogo, incorpore a levedura nutricional, sal e pimenta. Sirva com as folhas de sálvia crocantes por cima." },
    ],
    substitutions: [
        "**Arroz arbóreo:** Pode usar arroz carnaroli.",
        "**Vinho branco:** Se preferir não usar álcool, substitua por mais caldo de legumes com algumas gotas de limão.",
    ],
    chefTip: "O segredo de um bom risoto é mexer constantemente e ter paciência. Isso libera o amido do arroz, garantindo a cremosidade natural do prato.",
  },
  'sopa-cremosa-de-lentilha-vermelha': {
    title: "Sopa Cremosa de Lentilha Vermelha e Gengibre",
    author: "Ravi P.",
    difficulty: "Fácil",
    description: "Uma sopa reconfortante, nutritiva e muito rápida de fazer. A lentilha vermelha cozinha em minutos e o gengibre dá um toque picante e fresco que levanta o sabor. Perfeita para um jantar leve durante a semana.",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    category: "Zero Lactose",
    tags: ["Vegano", "Sem Glúten", "Sopa"],
    ingredients: [
        { value: "1 colher de sopa de óleo de coco" },
        { value: "1 cebola picada" },
        { value: "2 dentes de alho picados" },
        { value: "1 colher de sopa de gengibre fresco ralado" },
        { value: "1 colher de chá de cúrcuma em pó" },
        { value: "1 e 1/2 xícara de lentilha vermelha" },
        { value: "4 xícaras de caldo de legumes" },
        { value: "1 lata de leite de coco (400ml)" },
        { value: "Suco de 1/2 limão" },
        { value: "Coentro fresco picado para servir" },
    ],
    instructions: [
        { value: "Em uma panela grande, aqueça o óleo de coco e refogue a cebola, alho e gengibre." },
        { value: "Adicione a cúrcuma e cozinhe por 1 minuto." },
        { value: "Acrescente a lentilha vermelha (lavada e escorrida) e o caldo de legumes. Deixe ferver." },
        { value: "Reduza o fogo e cozinhe por cerca de 15 minutos, ou até a lentilha ficar bem macia." },
        { value: "Com um mixer de mão ou no liquidificador, bata a sopa até ficar cremosa." },
        { value: "Volte a sopa para a panela, adicione o leite de coco e o suco de limão. Aqueça sem deixar ferver." },
        { value: "Ajuste o sal e sirva com coentro fresco por cima." },
    ],
    substitutions: [
        "**Lentilha vermelha:** Pode ser substituída por lentilha amarela.",
        "**Leite de coco:** O leite de coco de latinha deixa a sopa mais cremosa, mas o de garrafinha também funciona.",
    ],
    chefTip: "Para uma textura extra, reserve um pouco da lentilha cozida antes de bater a sopa e adicione de volta no final. Assim você terá uma base cremosa com alguns grãos inteiros.",
  },
  'lasanha-de-berinjela-com-tofu': {
    title: "Lasanha de Berinjela com Ricota de Tofu",
    author: "Sandra T.",
    difficulty: "Médio",
    description: "Uma versão leve, sem glúten e sem lactose da clássica lasanha. As fatias de berinjela substituem a massa e a 'ricota' de tofu temperada dá a cremosidade e o sabor que a gente ama. É um prato surpreendente!",
    prepTime: 25,
    cookTime: 40,
    servings: 6,
    category: "Zero Lactose",
    tags: ["Vegano", "Sem Glúten", "Prato Principal"],
    ingredients: [
        { value: "2 berinjelas grandes" },
        { value: "Azeite, sal e pimenta" },
        { value: "Molho:" },
        { value: "1 cebola picada" },
        { value: "2 dentes de alho picados" },
        { value: "800g de tomate pelado em lata" },
        { value: "Manjericão fresco a gosto" },
        { value: "Ricota de Tofu:" },
        { value: "400g de tofu firme" },
        { value: "1/4 xícara de levedura nutricional" },
        { value: "Suco de 1 limão" },
        { value: "Sal e noz-moscada a gosto" },
    ],
    instructions: [
        { value: "Corte as berinjelas em fatias finas no sentido do comprimento. Pincele com azeite, tempere com sal e pimenta e grelhe ou asse até dourarem. Reserve." },
        { value: "Para o molho, refogue a cebola e o alho em azeite, adicione o tomate pelado, tempere e cozinhe por 15 minutos. Finalize com manjericão." },
        { value: "Para a ricota, amasse o tofu com um garfo e misture com levedura nutricional, suco de limão, sal e noz-moscada." },
        { value: "Monte a lasanha em um refratário: camada de molho, camada de berinjela, camada de ricota de tofu. Repita até acabarem os ingredientes, finalizando com molho." },
        { value: "Asse em forno pré-aquecido a 180°C por cerca de 30-40 minutos." },
    ],
    substitutions: [
        "**Berinjela:** Pode ser substituída por fatias de abobrinha.",
        "**Tofu:** Use um tofu de boa qualidade para uma 'ricota' mais saborosa. Se preferir, pode usar uma base de castanha de caju batida.",
    ],
    chefTip: "Deixe a berinjela de molho em água e sal por 30 minutos antes de grelhar. Isso ajuda a tirar o amargor e faz com que ela absorva menos óleo.",
  },
  'curry-de-legumes-com-leite-de-coco': {
    title: "Curry de Legumes com Leite de Coco",
    author: "Sofia R.",
    difficulty: "Fácil",
    description: "Um prato vibrante, aromático e cheio de sabor. Este curry é super versátil e você pode usar os legumes que tiver na geladeira. O leite de coco amacia a intensidade das especiarias, resultando em um molho cremoso e irresistível.",
    prepTime: 20,
    cookTime: 30,
    servings: 4,
    category: "Zero Lactose",
    tags: ["Vegano", "Sem Glúten", "Prato Principal"],
    ingredients: [
        { value: "2 colheres de sopa de óleo de coco" },
        { value: "1 cebola picada" },
        { value: "2 dentes de alho picados" },
        { value: "1 colher de sopa de gengibre ralado" },
        { value: "2 colheres de sopa de curry em pó" },
        { value: "1 batata-doce em cubos" },
        { value: "1 cenoura em rodelas" },
        { value: "1 pimentão vermelho em tiras" },
        { value: "1 xícara de brócolis em floretes" },
        { value: "1 lata (400ml) de leite de coco" },
        { value: "1 xícara de caldo de legumes" },
        { value: "1 xícara de espinafre fresco" },
        { value: "Sal e pimenta a gosto" },
        { value: "Coentro fresco para servir" },
    ],
    instructions: [
        { value: "Em uma panela grande, aqueça o óleo de coco e refogue a cebola, o alho e o gengibre." },
        { value: "Adicione o curry em pó e cozinhe por um minuto para liberar os aromas." },
        { value: "Acrescente a batata-doce e a cenoura, refogando por 5 minutos." },
        { value: "Adicione o pimentão, o leite de coco e o caldo de legumes. Tempere com sal e pimenta, deixe ferver e cozinhe por 15 minutos, ou até os legumes ficarem macios." },
        { value: "Junte o brócolis e cozinhe por mais 5 minutos." },
        { value: "Desligue o fogo, misture o espinafre até murchar e sirva com coentro fresco e arroz jasmim." },
    ],
    substitutions: [
        "**Legumes:** Use abobrinha, couve-flor, vagem, ervilha... o que preferir!",
        "**Proteína:** Para um prato mais substancioso, adicione grão-de-bico cozido ou cubos de tofu no final do cozimento.",
    ],
    chefTip: "Toste o curry em pó no óleo antes de adicionar os líquidos. Isso intensifica o sabor e o aroma das especiarias, fazendo toda a diferença no resultado final do prato.",
  },
  'panqueca-americana-vegana': {
    title: "Panqueca Americana Vegana",
    author: "Bia N.",
    difficulty: "Fácil",
    description: "O café da manhã de fim de semana perfeito! Essas panquecas são altas, fofinhas e deliciosas, e ninguém vai acreditar que não levam ovos nem leite. Sirva com frutas frescas e agave para uma refeição especial.",
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    category: "Zero Lactose",
    tags: ["Vegano", "Lanche", "Café da Manhã"],
    ingredients: [
        { value: "1 e 1/2 xícara de farinha de trigo" },
        { value: "2 colheres de sopa de açúcar" },
        { value: "1 colher de sopa de fermento em pó" },
        { value: "1/2 colher de chá de sal" },
        { value: "1 e 1/2 xícara de bebida vegetal (soja ou aveia)" },
        { value: "1 colher de sopa de vinagre de maçã" },
        { value: "2 colheres de sopa de óleo vegetal" },
    ],
    instructions: [
        { value: "Em uma tigela pequena, misture a bebida vegetal e o vinagre. Deixe descansar por 5 minutos para 'talhar'. Isso simula um buttermilk vegano." },
        { value: "Em outra tigela grande, misture a farinha, o açúcar, o fermento e o sal." },
        { value: "Despeje a mistura de 'buttermilk' e o óleo sobre os ingredientes secos. Mexa apenas o suficiente para incorporar. Não bata demais." },
        { value: "Aqueça uma frigideira antiaderente em fogo médio. Unte levemente com óleo." },
        { value: "Despeje 1/4 de xícara de massa por panqueca. Cozinhe por 2-3 minutos, ou até bolhas se formarem na superfície." },
        { value: "Vire e cozinhe por mais 1-2 minutos, até dourar. Sirva imediatamente." },
    ],
    substitutions: [
        "**Farinha:** Pode usar metade farinha de trigo integral para mais fibras, ou um mix de farinhas sem glúten para uma versão GF.",
        "**Açúcar:** Açúcar de coco ou demerara funcionam bem.",
    ],
    chefTip: "O segredo para panquecas fofinhas é não mexer a massa em excesso! Mexa apenas até os ingredientes secos e molhados se combinarem. Alguns grumos são bem-vindos e garantem a leveza da massa.",
  },
  'vatapa-vegano': {
    title: "Vatapá Vegano",
    author: "Dona Elza",
    difficulty: "Médio",
    description: "Uma versão vegana deste clássico da culinária baiana que aprendi com minha mãe. Substituímos o peixe por caju e o camarão por cogumelos, e o resultado é uma explosão de sabor e cremosidade. Um prato de festa!",
    prepTime: 20,
    cookTime: 30,
    servings: 6,
    category: "Zero Lactose",
    tags: ["Vegano", "Prato Principal", "Sem Glúten"],
    ingredients: [
        { value: "2 xícaras de castanha de caju torrada" },
        { value: "2 xícaras de pão sem glúten amanhecido em pedaços" },
        { value: "2 xícaras de leite de coco" },
        { value: "1/4 xícara de azeite de dendê" },
        { value: "1 cebola grande picada" },
        { value: "3 dentes de alho picados" },
        { value: "1 pimentão verde picado" },
        { value: "2 tomates picados" },
        { value: "200g de cogumelos shiitake fatiados" },
        { value: "1/2 xícara de coentro picado" },
        { value: "Sal e pimenta a gosto" },
    ],
    instructions: [
        { value: "No liquidificador, bata a castanha de caju com o pão e o leite de coco até formar um creme espesso. Reserve." },
        { value: "Em uma panela, aqueça o azeite de dendê e refogue a cebola, o alho e o pimentão." },
        { value: "Adicione os tomates e os cogumelos e cozinhe até amaciarem." },
        { value: "Despeje o creme de caju e pão na panela, mexendo constantemente para não grudar no fundo." },
        { value: "Cozinhe em fogo baixo por cerca de 15 minutos, até o creme engrossar e cozinhar bem." },
        { value: "Finalize com o coentro picado, ajuste o sal e a pimenta. Sirva com arroz branco e acarajé (se for o caso)." },
    ],
    substitutions: [
        "**Castanha de Caju:** Pode ser substituída por amendoim torrado sem pele.",
        "**Cogumelos:** Se não gostar, pode usar palmito desfiado ou jaca verde desfiada.",
    ],
    chefTip: "O ponto do vatapá é quando ele está cremoso, mas firme o suficiente para não escorrer no prato. Cozinhe em fogo baixo e mexa sem parar para atingir a consistência perfeita.",
  },
  'cookie-de-chocolate-vegano': {
    title: "Cookie com Gotas de Chocolate (Vegano)",
    author: "Fernanda L.",
    difficulty: "Fácil",
    description: "O cookie perfeito: crocante por fora, macio por dentro e cheio de chocolate derretido. Essa receita é super fácil e o resultado é impressionante. Ninguém vai dizer que é vegano!",
    prepTime: 15,
    cookTime: 12,
    servings: 12,
    category: "Zero Lactose",
    tags: ["Vegano", "Sobremesa"],
    ingredients: [
        { value: "1/2 xícara de óleo de coco derretido" },
        { value: "3/4 xícara de açúcar mascavo" },
        { value: "1/4 xícara de açúcar branco" },
        { value: "1/4 xícara de bebida vegetal (amêndoas, soja)" },
        { value: "1 colher de chá de extrato de baunilha" },
        { value: "1 e 1/2 xícara de farinha de trigo" },
        { value: "1/2 colher de chá de bicarbonato de sódio" },
        { value: "1/2 colher de chá de sal" },
        { value: "1 xícara de gotas de chocolate meio amargo (sem leite)" },
    ],
    instructions: [
        { value: "Pré-aqueça o forno a 180°C e forre uma assadeira com papel manteiga." },
        { value: "Em uma tigela, misture o óleo de coco e os açúcares. Adicione a bebida vegetal e a baunilha e misture bem." },
        { value: "Em outra tigela, peneire a farinha, o bicarbonato e o sal." },
        { value: "Adicione os ingredientes secos aos molhados e misture até incorporar. Não mexa demais." },
        { value: "Incorpore as gotas de chocolate." },
        { value: "Com uma colher de sorvete, faça bolinhas de massa e distribua na assadeira, deixando espaço entre elas." },
        { value: "Asse por 10-12 minutos, ou até as bordas estarem douradas. O centro ainda parecerá um pouco cru." },
        { value: "Deixe esfriar na assadeira por 5 minutos antes de transferir para uma grade." },
    ],
    substitutions: [
        "**Farinha de Trigo:** Para uma versão sem glúten, use um mix de farinha GF na mesma proporção.",
        "**Gotas de chocolate:** Pode usar chocolate em barra 70% cacau picado.",
        "**Açúcar:** Usar apenas açúcar mascavo deixará os cookies mais macios e úmidos.",
    ],
    chefTip: "Não asse os cookies demais! O segredo é tirá-los do forno quando as bordas estiverem firmes, mas o centro ainda parecer levemente mole. Eles continuarão a cozinhar no calor da assadeira e ficarão com a textura perfeita.",
  },
  'maionese-de-abacate': {
    title: "Maionese de Abacate",
    author: "Rodrigo F.",
    difficulty: "Fácil",
    description: "Uma alternativa incrível à maionese tradicional. Super cremosa, saudável e cheia de sabor. Perfeita para sanduíches, saladas ou como um dip para legumes.",
    prepTime: 5,
    cookTime: 0,
    servings: 4,
    category: "Zero Lactose",
    tags: ["Vegano", "Sem Glúten", "Molho"],
    ingredients: [
        { value: "1 abacate maduro" },
        { value: "Suco de 1 limão" },
        { value: "1 dente de alho pequeno" },
        { value: "2 colheres de sopa de azeite de oliva" },
        { value: "Coentro ou salsinha a gosto" },
        { value: "Sal e pimenta do reino a gosto" },
    ],
    instructions: [
        { value: "Coloque todos os ingredientes em um processador de alimentos ou liquidificador." },
        { value: "Bata até obter uma mistura completamente lisa e cremosa." },
        { value: "Prove e ajuste o sal, a pimenta ou o limão, se necessário." },
        { value: "Sirva imediatamente ou guarde na geladeira em um pote fechado com um filme plástico em contato com a superfície para não oxidar." },
    ],
    substitutions: [
        "**Limão:** Pode usar suco de lima para um sabor diferente.",
        "**Coentro/Salsinha:** Hortelã fresca também fica delicioso.",
    ],
    chefTip: "O limão não é apenas para dar sabor, ele é essencial para evitar que o abacate oxide e escureça. Não economize no suco de limão!",
  },
  'quibe-de-abobora-com-quinoa': {
    title: "Quibe de Abóbora com Quinoa",
    author: "Patricia C.",
    difficulty: "Médio",
    description: "Uma versão vegetariana e funcional do quibe tradicional. A abóbora traz umidade e um sabor adocicado, enquanto a quinoa substitui o trigo e adiciona proteína. Ótimo para assar e servir como lanche ou prato principal.",
    prepTime: 20,
    cookTime: 30,
    servings: 8,
    category: "Zero Lactose",
    tags: ["Vegano", "Sem Glúten", "Lanche"],
    ingredients: [
        { value: "2 xícaras de purê de abóbora cabotiá" },
        { value: "1 xícara de quinoa cozida" },
        { value: "1 cebola pequena picada" },
        { value: "1/2 xícara de hortelã fresca picada" },
        { value: "1/4 xícara de salsinha picada" },
        { value: "1 colher de chá de cominho em pó" },
        { value: "Sal e pimenta síria a gosto" },
        { value: "Azeite para untar" },
    ],
    instructions: [
        { value: "Em uma tigela grande, misture o purê de abóbora e a quinoa cozida." },
        { value: "Adicione a cebola, a hortelã, a salsinha, o cominho, o sal e a pimenta síria." },
        { value: "Misture tudo muito bem com as mãos até formar uma massa homogênea." },
        { value: "Unte um refratário com azeite e espalhe a massa do quibe." },
        { value: "Faça riscos na superfície com uma faca, formando losangos." },
        { value: "Regue com um fio de azeite e asse em forno pré-aquecido a 200°C por cerca de 30 minutos." },
    ],
    substitutions: [
        "**Quinoa:** Pode usar trigo para quibe (se não tiver restrição ao glúten) ou lentilha cozida e amassada.",
        "**Recheio:** Se quiser, pode fazer uma camada de recheio no meio com homus ou um refogado de espinafre.",
    ],
    chefTip: "Asse a abóbora em vez de cozinhar. Isso concentra o sabor e evita que o purê fique aguado, o que é crucial para a textura final do quibe.",
  },
  'bobo-de-palmito': {
    title: "Bobó de Palmito",
    author: "Chef Gabi",
    difficulty: "Médio",
    description: "Essa versão do bobó de camarão usa palmito pupunha para criar uma textura e sabor que lembram o prato original, mas de forma 100% vegetal. O creme de aipim e o azeite de dendê trazem toda a alma da Bahia para a sua mesa.",
    prepTime: 20,
    cookTime: 35,
    servings: 5,
    category: "Zero Lactose",
    tags: ["Vegano", "Sem Glúten", "Prato Principal"],
    ingredients: [
        { value: "500g de aipim (mandioca) descascado" },
        { value: "3 colheres de sopa de azeite de dendê" },
        { value: "1 cebola grande picada" },
        { value: "3 dentes de alho picados" },
        { value: "1 pimentão amarelo picado" },
        { value: "2 tomates picados" },
        { value: "1 vidro (300g) de palmito pupunha em rodelas" },
        { value: "200ml de leite de coco" },
        { value: "1/2 xícara de coentro picado" },
        { value: "Sal e pimenta a gosto" },
    ],
    instructions: [
        { value: "Cozinhe o aipim em água e sal até ficar muito macio. Escorra (reservando um pouco da água) e bata no liquidificador com o leite de coco até formar um creme liso. Se necessário, use a água do cozimento para ajudar a bater." },
        { value: "Em uma panela, aqueça o azeite de dendê e refogue a cebola, o alho e o pimentão." },
        { value: "Adicione o tomate e cozinhe até começar a desmanchar." },
        { value: "Junte o palmito e refogue por mais alguns minutos." },
        { value: "Despeje o creme de aipim na panela e misture bem. Cozinhe por cerca de 10 minutos." },
        { value: "Finalize com o coentro, ajuste o sal e a pimenta. Sirva quente." },
    ],
    substitutions: [
        "**Palmito:** Jaca verde desfiada ou cogumelos também funcionam muito bem como substitutos.",
        "**Aipim:** Pode usar batata-doce ou inhame para fazer o creme, mas o sabor e a textura originais vêm do aipim.",
    ],
    chefTip: "Use um aipim de boa qualidade, que cozinhe bem e não seja fibroso. Isso fará toda a diferença na cremosidade final do seu bobó.",
  },
  'sorvete-de-manga': {
    title: "Sorvete de Manga com 2 Ingredientes",
    author: "Luiza F.",
    difficulty: "Muito Fácil",
    description: "A sobremesa mais fácil e refrescante do mundo! Você só precisa de manga congelada e um toque de bebida vegetal para um sorvete super cremoso, natural e sem açúcar refinado. Perfeito para os dias quentes.",
    prepTime: 5,
    cookTime: 0,
    servings: 2,
    category: "Zero Lactose",
    tags: ["Vegano", "Sem Glúten", "Sobremesa Rápida"],
    ingredients: [
        { value: "2 mangas grandes e maduras, em cubos e congeladas" },
        { value: "2 a 4 colheres de sopa de bebida vegetal (coco, amêndoas)" },
    ],
    instructions: [
        { value: "Retire a manga do freezer e deixe descansar por 5 minutos." },
        { value: "Coloque a manga congelada em um processador de alimentos potente." },
        { value: "Comece a processar. Adicione a bebida vegetal, uma colher de cada vez." },
        { value: "Assim que atingir a consistência de sorvete, sirva imediatamente." },
    ],
    substitutions: [
        "**Manga:** Banana congelada (nice cream!) ou uma mistura de frutas vermelhas congeladas também ficam perfeitos.",
        "**Bebida vegetal:** Se a fruta estiver bem doce, pode usar água ou suco de laranja.",
    ],
    chefTip: "O segredo é usar um processador potente e ter paciência, parando para raspar as laterais. Não adicione muito líquido de uma vez.",
  },
    'torta-de-frango-cremosa-sem-lactose': {
    title: "Torta de 'Frango' Cremosa com Massa de Grão-de-Bico",
    author: "Chef Carla",
    difficulty: "Médio",
    description: "Essa torta é puro aconchego! A massa, feita com farinha de grão-de-bico, é nutritiva e sem glúten. O recheio cremoso usa jaca verde desfiada para simular frango, em um molho branco à base de inhame. Surpreendente!",
    prepTime: 30,
    cookTime: 40,
    servings: 8,
    category: "Zero Lactose",
    tags: ["Vegano", "Sem Glúten", "Lanche", "Prato Principal"],
    ingredients: [
      { value: "Massa:" },
      { value: "2 xícaras de farinha de grão-de-bico" },
      { value: "1/2 xícara de azeite de oliva" },
      { value: "1/2 colher de chá de sal" },
      { value: "4-6 colheres de sopa de água gelada" },
      { value: "Recheio:" },
      { value: "500g de jaca verde cozida e desfiada" },
      { value: "1 cebola picada" },
      { value: "2 dentes de alho picados" },
      { value: "1 tomate picado" },
      { value: "Azeitonas verdes picadas a gosto" },
      { value: "Molho Branco:" },
      { value: "2 inhames médios cozidos" },
      { value: "1 xícara da água do cozimento do inhame" },
      { value: "2 colheres de sopa de azeite" },
      { value: "Noz-moscada e sal a gosto" },
    ],
    instructions: [
      { value: "Para a massa, misture a farinha e o sal. Adicione o azeite e misture com os dedos. Adicione a água aos poucos. Deixe descansar por 20 minutos." },
      { value: "Para o recheio, refogue a cebola e o alho em azeite. Adicione a jaca desfiada e os temperos." },
      { value: "Para o molho, bata o inhame cozido com a água do cozimento, azeite, noz-moscada e sal." },
      { value: "Misture o molho branco ao recheio de jaca." },
      { value: "Abra 2/3 da massa e forre o fundo e as laterais de uma forma de torta." },
      { value: "Abra o restante da massa e cubra a torta." },
      { value: "Asse em forno pré-aquecido a 180°C por cerca de 40 minutos." },
    ],
    substitutions: [
      "**Jaca Verde:** Pode substituir por palmito desfiado ou cogumelos.",
      "**Farinha de Grão-de-Bico:** Se não tiver restrição ao glúten, pode usar farinha de trigo integral.",
    ],
    chefTip: "Para desfiar a jaca verde facilmente, cozinhe-a na panela de pressão com temperos.",
  },
  'arroz-doce-cremoso-com-leite-de-coco': {
    title: "Arroz Doce Cremoso com Leite de Coco e Canela",
    author: "Vó Maria",
    difficulty: "Fácil",
    description: "A receita de arroz doce da minha avó, adaptada para ser sem lactose. O leite de coco e as especiarias dão um toque exótico e uma cremosidade incomparável. É a sobremesa perfeita para uma noite fria.",
    prepTime: 5,
    cookTime: 40,
    servings: 6,
    category: "Zero Lactose",
    tags: ["Vegano", "Sem Glúten", "Sobremesa"],
    ingredients: [
      { value: "1 xícara de arroz branco" },
      { value: "2 xícaras de água" },
      { value: "1 pau de canela" },
      { value: "3 cravos-da-índia" },
      { value: "500ml de leite de coco (de garrafinha)" },
      { value: "1/2 xícara de açúcar (ou a gosto)" },
      { value: "Casca de 1/2 laranja (opcional)" },
      { value: "Canela em pó para polvilhar" },
    ],
    instructions: [
      { value: "Em uma panela, coloque o arroz, a água, a canela em pau, os cravos e a casca de laranja." },
      { value: "Leve ao fogo médio e cozinhe, mexendo de vez em quando." },
      { value: "Retire a casca de laranja, a canela e os cravos." },
      { value: "Adicione o leite de coco e o açúcar." },
      { value: "Cozinhe em fogo baixo, mexendo sempre, por cerca de 15-20 minutos." },
      { value: "Desligue o fogo e deixe amornar. Sirva em tigelas." },
    ],
    substitutions: [
      "**Leite de coco:** Para uma versão mais 'light', use bebida de aveia ou amêndoas.",
      "**Açúcar:** Açúcar demerara ou de coco funcionam bem.",
    ],
    chefTip: "Não lave o arroz antes de cozinhar! O amido presente no grão é o que ajuda a dar a cremosidade característica do arroz doce.",
  },
  'salpicao-vegano-com-batata-palha-caseira': {
    title: "Salpicão Vegano com Maionese de Castanha",
    author: "Julia G.",
    difficulty: "Médio",
    description: "Um clássico das festas de fim de ano em uma versão 100% vegetal, leve e deliciosa. A maionese de castanha de caju é o segredo para a cremosidade, e a batata palha caseira dá o toque crocante final.",
    prepTime: 25,
    cookTime: 15,
    servings: 8,
    category: "Zero Lactose",
    tags: ["Vegano", "Sem Glúten", "Salada", "Acompanhamento"],
    ingredients: [
      { value: "2 xícaras de grão-de-bico cozido e amassado grosseiramente" },
      { value: "1 cenoura grande ralada" },
      { value: "1 maçã verde em cubinhos" },
      { value: "1/2 xícara de uvas passas (opcional)" },
      { value: "1/2 xícara de milho verde cozido" },
      { value: "Salsinha e cebolinha picadas a gosto" },
      { value: "Maionese de Castanha:" },
      { value: "1 xícara de castanha de caju crua, demolhada por 4h" },
      { value: "1/2 xícara de água" },
      { value: "2 colheres de sopa de suco de limão" },
      { value: "1 dente de alho pequeno" },
      { value: "Sal a gosto" },
    ],
    instructions: [
      { value: "Para a maionese, escorra as castanhas e bata todos os ingredientes no liquidificador." },
      { value: "Em uma tigela grande, misture o grão-de-bico, a cenoura, a maçã, as passas, o milho." },
      { value: "Incorpore a maionese de castanha gelada à mistura de legumes e grãos." },
      { value: "Ajuste o sal se necessário." },
      { value: "Sirva frio, coberto com batata palha." },
    ],
    substitutions: [
      "**Grão-de-bico:** Pode usar a mesma quantidade de jaca verde desfiada ou palmito picado.",
      "**Maçã:** Para um toque agridoce, pode substituir por cubos de abacaxi ou manga.",
    ],
    chefTip: "Deixe a maionese de castanha bem gelada antes de misturar aos outros ingredientes.",
  },
  'farofa-de-banana-com-cebola-crocante': {
    title: "Farofa de Banana com Cebola Crocante",
    author: "Tiago M.",
    difficulty: "Fácil",
    description: "Acompanhamento perfeito para qualquer prato principal. O doce da banana contrasta com a cebola frita e a textura da farinha de mandioca. Viciante!",
    prepTime: 10,
    cookTime: 20,
    servings: 6,
    category: "Zero Lactose",
    tags: ["Vegano", "Sem Glúten", "Acompanhamento"],
    ingredients: [
      { value: "1/2 xícara de azeite de oliva" },
      { value: "2 cebolas grandes fatiadas finamente" },
      { value: "3 bananas-da-terra maduras, mas firmes, em rodelas" },
      { value: "2 xícaras de farinha de mandioca flocada (biju)" },
      { value: "Sal e cheiro-verde picado a gosto" },
    ],
    instructions: [
      { value: "Em uma frigideira grande, aqueça o azeite em fogo médio-alto." },
      { value: "Adicione a cebola fatiada e frite." },
      { value: "Retire metade da cebola e reserve." },
      { value: "Na mesma frigideira, adicione as rodelas de banana e frite." },
      { value: "Reduza o fogo para o mínimo, adicione a farinha de mandioca aos poucos." },
      { value: "Cozinhe por cerca de 5 minutos, mexendo sempre." },
      { value: "Desligue o fogo, ajuste o sal, misture o cheiro-verde e a cebola crocante." },
    ],
    substitutions: [
      "**Banana-da-terra:** Banana nanica também funciona.",
      "**Azeite:** Pode ser substituído por óleo de coco.",
    ],
    chefTip: "A paciência é a chave para a cebola crocante.",
  },
  'quiche-sem-queijo-de-alho-poro': {
    title: "Quiche de Alho-Poró com Massa Grão-de-Bico",
    author: "Ana P.",
    difficulty: "Médio",
    description: "Uma quiche elegante e saborosa, perfeita para um brunch ou almoço leve. A massa é sem glúten e o recheio cremoso é feito com tofu e alho-poró refogado. Ninguém vai sentir falta do queijo ou do creme de leite!",
    prepTime: 25,
    cookTime: 45,
    servings: 6,
    category: "Zero Lactose",
    tags: ["Vegano", "Sem Glúten", "Prato Principal"],
    ingredients: [
      { value: "Massa:" },
      { value: "1 e 1/2 xícara de farinha de grão-de-bico" },
      { value: "1/2 xícara de farinha de amêndoas" },
      { value: "1/3 xícara de azeite de oliva" },
      { value: "1/4 xícara de água gelada" },
      { value: "1/2 colher de chá de sal" },
      { value: "Recheio:" },
      { value: "2 talos de alho-poró fatiados" },
      { value: "300g de tofu firme" },
      { value: "1/2 xícara de bebida vegetal sem açúcar" },
      { value: "3 colheres de sopa de levedura nutricional" },
      { value: "Sal, pimenta e noz-moscada a gosto" },
    ],
    instructions: [
      { value: "Para a massa, misture as farinhas e o sal. Adicione o azeite e incorpore. Forre uma forma de quiche." },
      { value: "Para o recheio, refogue o alho-poró em um fio de azeite." },
      { value: "No processador, bata o tofu, a bebida vegetal, a levedura nutricional e os temperos." },
      { value: "Misture o creme de tofu com o alho-poró refogado." },
      { value: "Despeje o recheio sobre a massa." },
      { value: "Asse por mais 30 minutos." },
    ],
    substitutions: [
      "**Alho-Poró:** Pode substituir por um refogado de espinafre com cogumelos.",
      "**Farinha de Amêndoas:** Pode usar farinha de aveia na mesma proporção.",
    ],
    chefTip: "Pré-assar a massa ('blind bake') é fundamental para que ela fique crocante.",
  },
  'sopa-de-tomate-assado': {
    title: "Sopa de Tomate Assado com Manjericão",
    author: "Marco B.",
    difficulty: "Fácil",
    description: "Assar os tomates antes de fazer a sopa intensifica a doçura e cria um sabor profundo e defumado. Um fio de 'creme' de castanhas finaliza com perfeição.",
    prepTime: 15,
    cookTime: 45,
    servings: 4,
    category: "Zero Lactose",
    tags: ["Vegano", "Sem Glúten", "Sopa"],
    ingredients: [
      { value: "1kg de tomates italianos maduros" },
      { value: "1 cebola roxa grande" },
      { value: "4 dentes de alho com casca" },
      { value: "Azeite de oliva" },
      { value: "Sal e pimenta do reino" },
      { value: "3 xícaras de caldo de legumes" },
      { value: "1 xícara de folhas de manjericão fresco" },
      { value: "Opcional: 1/4 xícara de castanha de caju crua, demolhada" },
    ],
    instructions: [
      { value: "Pré-aqueça o forno a 200°C. Corte os tomates e a cebola. Em uma assadeira, misture com os dentes de alho." },
      { value: "Asse por cerca de 30-40 minutos." },
      { value: "Esprema os dentes de alho para fora da casca." },
      { value: "Transfira os vegetais assados para um liquidificador." },
      { value: "Bata tudo até obter um creme completamente liso." },
      { value: "Aqueça a sopa em uma panela, ajuste o sal e a pimenta." },
    ],
    substitutions: [
      "**Tomate Italiano:** Pode usar outro tipo de tomate, desde que esteja bem maduro.",
      "**Manjericão:** Orégano fresco também combina muito bem.",
    ],
    chefTip: "Não tenha medo de deixar os vegetais tostarem um pouco no forno.",
  },
  'hamburguer-de-lentilha': {
    title: "Hambúrguer de Lentilha Defumado",
    author: "Daniel R.",
    difficulty: "Médio",
    description: "Este não é um hambúrguer vegetal sem graça! A combinação de lentilha com cogumelos, nozes e um toque de fumaça líquida cria um sabor e uma textura incríveis.",
    prepTime: 20,
    cookTime: 20,
    servings: 4,
    category: "Zero Lactose",
    tags: ["Vegano", "Lanche", "Sem Glúten"],
    ingredients: [
      { value: "1 xícara de lentilha marrom cozida e bem escorrida" },
      { value: "1/2 xícara de nozes picadas" },
      { value: "150g de cogumelos paris picados" },
      { value: "1 cebola pequena picada" },
      { value: "2 colheres de sopa de farinha de aveia (sem glúten)" },
      { value: "1 colher de sopa de shoyu (tamari para versão GF)" },
      { value: "1 colher de chá de páprica defumada" },
      { value: "1/2 colher de chá de fumaça líquida (opcional)" },
      { value: "Sal e pimenta a gosto" },
    ],
    instructions: [
      { value: "Em uma frigideira, refogue a cebola e os cogumelos." },
      { value: "Em um processador de alimentos, pulse grosseiramente a lentilha cozida e as nozes." },
      { value: "Transfira a mistura para uma tigela e adicione os cogumelos refogados." },
      { value: "Misture bem com as mãos, tempere com sal e pimenta." },
      { value: "Modele 4 hambúrgueres." },
      { value: "Grelhe os hambúrgueres em uma frigideira com um pouco de azeite." },
      { value: "Sirva no pão com seus acompanhamentos preferidos." },
    ],
    substitutions: [
      "**Lentilha:** Feijão preto cozido e bem escorrido é um ótimo substituto.",
      "**Nozes:** Sementes de girassol ou castanha-do-pará podem ser usadas.",
    ],
    chefTip: "O segredo para um hambúrguer vegetal que não desmancha é remover o excesso de umidade.",
  },
  'brownie-vegano-funcional': {
    title: "Brownie de Batata Doce (Vegano)",
    author: "Mariana F.",
    difficulty: "Fácil",
    description: "Sim, você leu certo: batata doce! Ela é o ingrediente secreto que deixa este brownie incrivelmente úmido e denso, sem a necessidade de ovos ou manteiga.",
    prepTime: 15,
    cookTime: 25,
    servings: 9,
    category: "Zero Lactose",
    tags: ["Vegano", "Sem Glúten", "Sobremesa"],
    ingredients: [
      { value: "1 xícara de purê de batata doce cozida" },
      { value: "1/2 xícara de pasta de amendoim" },
      { value: "1/4 xícara de melado de cana ou maple syrup" },
      { value: "1/4 xícara de cacau em pó" },
      { value: "1/2 xícara de farinha de aveia (sem glúten)" },
      { value: "1 colher de chá de fermento em pó" },
      { value: "1/2 xícara de gotas de chocolate meio amargo" },
    ],
    instructions: [
      { value: "Pré-aqueça o forno a 180°C e unte uma forma quadrada pequena (20x20cm)." },
      { value: "Em uma tigela grande, misture o purê de batata doce, a pasta de amendoim e o melado." },
      { value: "Peneire por cima o cacau em pó, a farinha de aveia e o fermento." },
      { value: "Incorpore as gotas de chocolate." },
      { value: "Despeje a massa na forma, alise a superfície e salpique o restante das gotas de chocolate." },
      { value: "Asse por 20-25 minutos." },
      { value: "Deixe esfriar completamente na forma antes de cortar." },
    ],
    substitutions: [
      "**Batata Doce:** Purê de abóbora também funciona.",
      "**Pasta de Amendoim:** Pode usar pasta de amêndoas ou de castanha de caju.",
    ],
    chefTip: "Cozinhe a batata doce no vapor ou asse em vez de ferver em água.",
  },
  'molho-pesto-de-rucula': {
    title: "Molho Pesto de Rúcula e Amêndoas",
    author: "Chef Rafa",
    difficulty: "Muito Fácil",
    description: "Uma variação do pesto tradicional com um toque picante e ousado da rúcula. As amêndoas trazem uma cremosidade suave.",
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    category: "Zero Lactose",
    tags: ["Vegano", "Sem Glúten", "Molho"],
    ingredients: [
      { value: "2 xícaras de folhas de rúcula frescas" },
      { value: "1/2 xícara de amêndoas sem pele" },
      { value: "1/2 xícara de azeite de oliva extra virgem" },
      { value: "2 dentes de alho" },
      { value: "3 colheres de sopa de levedura nutricional" },
      { value: "Suco de 1/2 limão" },
      { value: "Sal e pimenta do reino a gosto" },
    ],
    instructions: [
      { value: "Em uma frigideira seca, toste levemente as amêndoas em fogo baixo." },
      { value: "No processador de alimentos, coloque a rúcula, as amêndoas tostadas e o suco de limão." },
      { value: "Pulse algumas vezes." },
      { value: "Com o processador ligado, adicione o azeite em um fio contínuo." },
      { value: "Tempere com sal e pimenta a gosto." },
    ],
    substitutions: [
      "**Rúcula:** Pode usar uma mistura de manjericão e espinafre.",
      "**Amêndoas:** Castanha-do-pará ou sementes de girassol são ótimos substitutos.",
    ],
    chefTip: "Para um pesto mais vibrante e menos amargo, retire os talos mais grossos da rúcula.",
  },
  'ceviche-de-manga-com-pimenta-biquinho': {
    title: "Ceviche de Manga com Pimenta Biquinho",
    author: "Lia S.",
    difficulty: "Fácil",
    description: "Uma entrada ou aperitivo tropical, refrescante e surpreendente.",
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    category: "Zero Lactose",
    tags: ["Vegano", "Sem Glúten", "Entrada", "Aperitivo"],
    ingredients: [
      { value: "2 mangas Palmer maduras, mas firmes, em cubos" },
      { value: "1 cebola roxa pequena em fatias finas" },
      { value: "1/2 xícara de pimenta biquinho, sem o líquido da conserva" },
      { value: "Suco de 3 limões tahiti" },
      { value: "1/2 xícara de coentro fresco picado" },
      { value: "1 colher de sopa de azeite de oliva" },
      { value: "Sal a gosto" },
    ],
    instructions: [
      { value: "Deixe as fatias de cebola roxa de molho em água com gelo." },
      { value: "Em uma tigela de vidro, misture delicadamente a manga em cubos." },
      { value: "Regue com o suco de limão e o azeite." },
      { value: "Incorpore o coentro picado." },
      { value: "Cubra e leve à geladeira por pelo menos 15 minutos." },
      { value: "Sirva frio." },
    ],
    substitutions: [
      "**Manga:** Mamão papaya ou pêssego firme também ficam deliciosos.",
      "**Pimenta Biquinho:** Se não encontrar, pode usar pimentão vermelho em cubinhos bem pequenos.",
    ],
    chefTip: "O 'leche de tigre' (o suco que se forma no fundo do ceviche) é a alma do prato.",
  },
  'nhoque-de-batata-doce-ao-sugo': {
    title: "Nhoque de Batata-Doce ao Sugo Rústico",
    author: "Vovó Helena",
    difficulty: "Médio",
    description: "Uma versão mais nutritiva e colorida do nhoque tradicional.",
    prepTime: 30,
    cookTime: 40,
    servings: 4,
    category: "Zero Lactose",
    tags: ["Vegano", "Prato Principal", "Sem Glúten"],
    ingredients: [
      { value: "Nhoque:" },
      { value: "1kg de batata-doce roxa" },
      { value: "1 e 1/2 xícara de mix de farinha sem glúten (aproximadamente)" },
      { value: "Sal a gosto" },
      { value: "Molho Sugo:" },
      { value: "2 colheres de sopa de azeite" },
      { value: "1 cebola picada" },
      { value: "2 dentes de alho picados" },
      { value: "800g de tomate pelado" },
      { value: "Folhas de manjericão fresco" },
    ],
    instructions: [
      { value: "Asse as batatas-doces no forno. Espere amornar, descasque e passe por um espremedor." },
      { value: "Em uma superfície limpa, coloque o purê de batata, adicione o sal e vá adicionando a farinha aos poucos." },
      { value: "Faça rolinhos com a massa e corte os nhoques." },
      { value: "Para o molho, refogue a cebola e o alho no azeite." },
      { value: "Adicione o tomate pelado, amasse com uma colher, tempere com sal." },
      { value: "Finalize o molho com as folhas de manjericão." },
    ],
    substitutions: [
      "**Batata-doce roxa:** Pode usar a batata-doce comum ou batata baroa (mandioquinha).",
      "**Farinha sem glúten:** Use uma mistura de farinha de arroz e polvilho doce.",
    ],
    chefTip: "O segredo do nhoque leve é usar o mínimo de farinha possível.",
  },
  'homus-de-beterraba': {
    title: "Homus de Beterraba",
    author: "Yasmin Z.",
    difficulty: "Fácil",
    description: "Uma variação vibrante e deliciosa do homus tradicional. A beterraba adiciona uma cor espetacular, um sabor adocicado.",
    prepTime: 10,
    cookTime: 40,
    servings: 6,
    category: "Zero Lactose",
    tags: ["Vegano", "Sem Glúten", "Aperitivo", "Pasta"],
    ingredients: [
      { value: "1 beterraba média, cozida ou assada" },
      { value: "1 lata (400g) de grão-de-bico cozido e escorrido" },
      { value: "1/4 xícara de tahine (pasta de gergelim)" },
      { value: "Suco de 1 limão" },
      { value: "2 dentes de alho" },
      { value: "3 colheres de sopa de azeite de oliva" },
      { value: "Sal e cominho em pó a gosto" },
    ],
    instructions: [
      { value: "Descasque a beterraba cozida e corte em pedaços." },
      { value: "No processador de alimentos, coloque a beterraba, o grão-de-bico, o tahine." },
      { value: "Bata até obter uma pasta grossa." },
      { value: "Com o processador ligado, adicione o azeite em fio." },
      { value: "Tempere com sal e cominho a gosto." },
      { value: "Sirva em uma tigela." },
    ],
    substitutions: [
      "**Grão-de-bico:** Feijão branco cozido pode ser usado para uma versão mais suave.",
      "**Tahine:** Se não tiver, pode omitir, mas o sabor característico do homus vem dele.",
    ],
    chefTip: "Para um homus extra cremoso, cozinhe o grão-de-bico em casa.",
  },
  'falafel-assado': {
    title: "Falafel Assado com Molho de Tahine",
    author: "David L.",
    difficulty: "Médio",
    description: "Uma versão mais leve do clássico bolinho de grão-de-bico.",
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    category: "Zero Lactose",
    tags: ["Vegano", "Sem Glúten", "Lanche"],
    ingredients: [
      { value: "Falafel:" },
      { value: "2 xícaras de grão-de-bico cru, demolhado por 12 horas" },
      { value: "1 cebola pequena picada" },
      { value: "1 xícara de salsinha fresca" },
      { value: "1 xícara de coentro fresco" },
      { value: "3 dentes de alho" },
      { value: "1 colher de chá de cominho em pó" },
      { value: "Sal e pimenta a gosto" },
      { value: "Molho:" },
      { value: "1/2 xícara de tahine" },
      { value: "Suco de 1 limão" },
      { value: "1/4 xícara de água" },
      { value: "1 dente de alho picado" },
    ],
    instructions: [
      { value: "Pré-aqueça o forno a 200°C." },
      { value: "Escorra muito bem o grão-de-bico demolhado." },
      { value: "No processador, coloque o grão-de-bico e todos os outros ingredientes." },
      { value: "Pulse até formar uma massa grossa e granulada." },
      { value: "Modele bolinhos." },
      { value: "Pincele os bolinhos com azeite." },
      { value: "Enquanto assa, prepare o molho misturando todos os ingredientes." },
      { value: "Sirva o falafel quente com o molho de tahine." },
    ],
    substitutions: [
      "**Ervas:** Pode usar uma mistura de hortelã e endro para um sabor diferente.",
      "**Grão-de-bico:** Fava seca e demolhada é a base do falafel original egípcio.",
    ],
    chefTip: "O erro mais comum ao fazer falafel é usar grão-de-bico cozido.",
  },
  'sopa-fria-de-pepino-e-abacate': {
    title: "Sopa Fria de Pepino e Abacate (Gaspacho Verde)",
    author: "Chef Helena",
    difficulty: "Fácil",
    description: "Uma sopa incrivelmente refrescante e elegante.",
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    category: "Zero Lactose",
    tags: ["Vegano", "Sem Glúten", "Sopa", "Entrada"],
    ingredients: [
      { value: "2 pepinos japoneses grandes, sem sementes" },
      { value: "1 abacate maduro" },
      { value: "1 pimentão verde pequeno" },
      { value: "1/2 cebola pequena" },
      { value: "1 dente de alho" },
      { value: "1/4 xícara de folhas de hortelã fresca" },
      { value: "Suco de 1 limão" },
      { value: "2 colheres de sopa de azeite de oliva" },
      { value: "1 xícara de água gelada" },
      { value: "Sal e pimenta branca a gosto" },
    ],
    instructions: [
      { value: "Pique grosseiramente todos os vegetais." },
      { value: "Coloque todos os ingredientes, exceto a água, no liquidificador." },
      { value: "Bata em alta velocidade até obter um creme liso." },
      { value: "Adicione a água gelada aos poucos, batendo." },
      { value: "Passe a sopa por uma peneira fina." },
      { value: "Leve à geladeira por pelo menos 30 minutos." },
      { value: "Sirva bem gelada, decorada com um fio de azeite." },
    ],
    substitutions: [
      "**Pepino:** Pode usar abobrinha crua para um sabor mais suave.",
      "**Hortelã:** Coentro ou manjericão também criam combinações deliciosas.",
    ],
    chefTip: "Sirva esta sopa em copinhos de shot como um aperitivo sofisticado.",
  },
  'escondidinho-de-carne-de-jaca': {
    title: "Escondidinho de 'Carne' de Jaca com Purê de Mandioquinha",
    author: "Bruno C.",
    difficulty: "Médio",
    description: "Uma versão vegana do clássico nordestino.",
    prepTime: 30,
    cookTime: 50,
    servings: 6,
    category: "Zero Lactose",
    tags: ["Vegano", "Sem Glúten", "Prato Principal"],
    ingredients: [
      { value: "Recheio:" },
      { value: "500g de jaca verde cozida e desfiada" },
      { value: "1 cebola picada" },
      { value: "2 dentes de alho picados" },
      { value: "1 tomate picado" },
      { value: "1/2 xícara de molho de tomate" },
      { value: "Cominho, páprica, sal e pimenta a gosto" },
      { value: "Purê:" },
      { value: "800g de mandioquinha (batata baroa) descascada" },
      { value: "2 colheres de sopa de azeite de oliva" },
      { value: "Sal a gosto" },
    ],
    instructions: [
      { value: "Para o recheio, refogue a cebola e o alho em azeite." },
      { value: "Para o purê, cozinhe a mandioquinha em água e sal." },
      { value: "Em um refratário, coloque a 'carne' de jaca no fundo." },
      { value: "Leve ao forno pré-aquecido a 200°C por cerca de 20 minutos." },
    ],
    substitutions: [
      "**Jaca:** Pode substituir por shimeji desfiado ou proteína de soja texturizada.",
      "**Mandioquinha:** Purê de batata-doce ou de aipim também ficam divinos.",
    ],
    chefTip: "O segredo da jaca desfiada é cozinhá-la na pressão com temperos.",
  },
  'paella-vegetariana': {
    title: "Paella Vegetariana",
    author: "Sofia L.",
    difficulty: "Difícil",
    description: "Uma versão colorida e vibrante do clássico espanhol.",
    prepTime: 25,
    cookTime: 40,
    servings: 6,
    category: "Zero Lactose",
    tags: ["Vegano", "Sem Glúten", "Prato Principal"],
    ingredients: [
      { value: "3 colheres de sopa de azeite de oliva" },
      { value: "1 cebola picada" },
      { value: "1 pimentão vermelho em tiras" },
      { value: "1 pimentão amarelo em tiras" },
      { value: "2 dentes de alho picados" },
      { value: "2 xícaras de arroz bomba ou parboilizado" },
      { value: "1 colher de chá de páprica doce" },
      { value: "Alguns pistilos de açafrão" },
      { value: "5 xícaras de caldo de legumes quente" },
      { value: "1 xícara de vagem picada" },
      { value: "1 xícara de ervilhas frescas ou congeladas" },
      { value: "1 lata de corações de alcachofra em conserva, escorridos" },
      { value: "Sal e gomos de limão para servir" },
    ],
    instructions: [
      { value: "Em uma paellera, aqueça o azeite e refogue a cebola e os pimentões." },
      { value: "Adicione o alho e a páprica." },
      { value: "Acrescente o arroz e frite, mexendo." },
      { value: "Dissolva o açafrão no caldo de legumes quente." },
      { value: "Quando começar a ferver, reduza o fogo." },
      { value: "Continue cozinhando por mais 10-15 minutos." },
      { value: "Aumente o fogo no último minuto para criar o 'socarrat'." },
      { value: "Desligue o fogo, cubra com um pano e deixe descansar por 5 minutos." },
    ],
    substitutions: [
      "**Vegetais:** Aspargos, brócolis e cogumelos são ótimas adições.",
      "**Arroz:** Se não encontrar o arroz bomba, o parboilizado é a melhor alternativa.",
    ],
    chefTip: "O maior segredo da paella é não mexer no arroz depois que o caldo é adicionado.",
  },
  'tabule-de-couve-flor': {
    title: "Tabule de Couve-Flor",
    author: "Samira H.",
    difficulty: "Fácil",
    description: "Uma versão low-carb, sem glúten e super refrescante do tabule.",
    prepTime: 20,
    cookTime: 0,
    servings: 4,
    category: "Zero Lactose",
    tags: ["Vegano", "Sem Glúten", "Salada"],
    ingredients: [
      { value: "1 cabeça de couve-flor pequena" },
      { value: "1 pepino japonês em cubinhos" },
      { value: "2 tomates sem sementes em cubinhos" },
      { value: "1 xícara de salsinha fresca picada" },
      { value: "1/2 xícara de hortelã fresca picada" },
      { value: "1/2 cebola roxa pequena picada" },
      { value: "Suco de 2 limões" },
      { value: "1/4 xícara de azeite de oliva extra virgem" },
      { value: "Sal e pimenta do reino a gosto" },
    ],
    instructions: [
      { value: "Lave a couve-flor e separe os floretes. Coloque no processador de alimentos." },
      { value: "Transfira a couve-flor processada para uma tigela grande." },
      { value: "Adicione o pepino, o tomate, a salsinha, a hortelã e a cebola roxa." },
      { value: "Em uma tigela pequena, faça o molho batendo o suco de limão, o azeite." },
      { value: "Regue a salada com o molho." },
      { value: "Deixe na geladeira por pelo menos 15 minutos." },
    ],
    substitutions: [
      "**Couve-flor:** Brócolis cru processado também funciona.",
      "**Adicional:** Grão-de-bico cozido ou sementes de romã dão um toque especial.",
    ],
    chefTip: "Para um tabule menos 'aguado', salgue o pepino em cubos e deixe escorrer em uma peneira.",
  },
  'chips-de-couve-com-levedura-nutricional': {
    title: "Chips de Couve com 'Sabor Queijo'",
    author: "Lucas Fit",
    difficulty: "Fácil",
    description: "Um snack crocante, saudável e viciante!",
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    category: "Zero Lactose",
    tags: ["Vegano", "Sem Glúten", "Lanche", "Snack"],
    ingredients: [
      { value: "1 maço de couve manteiga" },
      { value: "1 colher de sopa de azeite de oliva" },
      { value: "3 colheres de sopa de levedura nutricional" },
      { value: "1/2 colher de chá de alho em pó" },
      { value: "1/2 colher de chá de sal" },
    ],
    instructions: [
      { value: "Pré-aqueça o forno a 150°C." },
      { value: "Lave e seque muito bem as folhas de couve." },
      { value: "Rasgue as folhas em pedaços." },
      { value: "Em uma tigela grande, coloque a couve e o azeite." },
      { value: "Em uma tigela pequena, misture a levedura nutricional." },
      { value: "Espalhe a couve em uma única camada." },
      { value: "Asse por 10-15 minutos." },
      { value: "Deixe esfriar completamente antes de comer." },
    ],
    substitutions: [
      "**Couve:** Folhas de espinafre também funcionam.",
      "**Tempero:** Páprica defumada ou pimenta caiena dão um toque picante delicioso.",
    ],
    chefTip: "O segredo para chips de couve que não murcham é assar em temperatura baixa.",
  },
  'creme-de-milho-vegano': {
    title: "Creme de Milho Vegano",
    author: "Tia Alice",
    difficulty: "Fácil",
    description: "Um clássico da comida caseira brasileira em sua melhor versão sem lactose.",
    prepTime: 5,
    cookTime: 15,
    servings: 4,
    category: "Zero Lactose",
    tags: ["Vegano", "Acompanhamento", "Sem Glúten"],
    ingredients: [
      { value: "2 latas de milho verde, escorrido" },
      { value: "1 xícara de bebida vegetal (aveia ou castanha)" },
      { value: "1 colher de sopa de azeite" },
      { value: "1/2 cebola pequena picada" },
      { value: "1 dente de alho picado" },
      { value: "Sal e noz-moscada a gosto" },
      { value: "Cheiro-verde para finalizar" },
    ],
    instructions: [
      { value: "No liquidificador, bata uma lata de milho com a bebida vegetal." },
      { value: "Em uma panela, aqueça o azeite e refogue a cebola e o alho." },
      { value: "Adicione a outra lata de milho." },
      { value: "Despeje o creme de milho batido na panela." },
      { value: "Cozinhe em fogo baixo, mexendo sempre." },
      { value: "Tempere com sal e uma pitada de noz-moscada." },
      { value: "Sirva quente, finalizado com cheiro-verde picado." },
    ],
    substitutions: [
      "**Milho em lata:** Pode usar a mesma quantidade de milho fresco debulhado e cozido.",
      "**Bebida Vegetal:** Leite de coco também confere uma cremosidade especial.",
    ],
    chefTip: "Bater apenas metade do milho dá uma textura muito mais interessante ao creme.",
  },
  'shake-proteico-de-banana-e-pasta-de-amendoim': {
    title: "Shake Proteico de Banana e Pasta de Amendoim",
    author: "Leo Maromba",
    difficulty: "Muito Fácil",
    description: "Um shake delicioso e nutritivo para o pós-treino ou um café da manhã reforçado.",
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    category: "Zero Lactose",
    tags: ["Vegano", "Bebida", "Café da Manhã", "Snack", "Sem Glúten"],
    ingredients: [
      { value: "1 banana prata congelada" },
      { value: "1 scoop de proteína vegetal sabor baunilha ou chocolate" },
      { value: "1 colher de sopa de pasta de amendoim integral" },
      { value: "1 colher de sopa de sementes de chia" },
      { value: "1 e 1/2 xícara de bebida vegetal gelada (amêndoas, soja)" },
    ],
    instructions: [
      { value: "Coloque todos os ingredientes no liquidificador." },
      { value: "Bata em alta velocidade até a mistura ficar homogênea e cremosa." },
      { value: "Se preferir um shake mais fino, adicione um pouco mais de bebida vegetal." },
      { value: "Sirva imediatamente." },
    ],
    substitutions: [
      "**Proteína Vegetal:** Se não tiver, o shake continua nutritivo.",
      "**Pasta de Amendoim:** Pasta de amêndoas ou de castanhas também funcionam bem.",
      "**Banana:** Pode usar 1/2 abacate para uma versão com menos açúcar.",
    ],
    chefTip: "Usar a banana congelada é o truque para um shake super cremoso e gelado.",
  },
'macarrao-com-molho-de-abobora-e-espinafre': {
    title: "Macarrão com Molho de Abóbora e Espinafre",
    author: "Giulia R.",
    difficulty: "Fácil",
    description: "Um prato de massa incrivelmente cremoso sem usar uma gota de laticínios!",
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    category: "Zero Lactose",
    tags: ["Vegano", "Prato Principal", "Sem Glúten"],
    ingredients: [
        { value: "400g de macarrão sem glúten (penne, fusilli)" },
        { value: "2 colheres de sopa de azeite" },
        { value: "1 cebola picada" },
        { value: "2 xícaras de purê de abóbora cabotiá" },
        { value: "1/2 xícara de bebida vegetal (aveia, castanhas)" },
        { value: "1/4 xícara de levedura nutricional" },
        { value: "3 xícaras de folhas de espinafre fresco" },
        { value: "Sal, pimenta e noz-moscada a gosto" },
        { value: "Sementes de abóbora tostadas para servir (opcional)" },
    ],
    instructions: [
        { value: "Cozinhe o macarrão de acordo com as instruções da embalagem." },
        { value: "Enquanto o macarrão cozinha, aqueça o azeite em uma panela grande." },
        { value: "Adicione o purê de abóbora, a bebida vegetal e a levedura nutricional." },
        { value: "Cozinhe o molho por cerca de 5 minutos." },
        { value: "Adicione as folhas de espinafre e mexa até que murchem." },
        { value: "Incorpore o macarrão cozido ao molho, misturando bem." },
        { value: "Sirva quente, com sementes de abóbora tostadas por cima." },
    ],
    substitutions: [
        "**Abóbora:** Batata-doce amassada também pode ser a base do molho.",
        "**Espinafre:** Couve fatiada finamente ou brócolis em pequenos floretes são boas alternativas.",
    ],
    chefTip: "A água do cozimento do macarrão é rica em amido e ajuda a emulsionar e engrossar o molho.",
  },
  'salada-de-batata-vegana': {
    title: "Salada de Batata Alemã (Versão Vegana)",
    author: "Klaus W.",
    difficulty: "Fácil",
    description: "Diferente da salada de batata com maionese, a versão alemã leva um molho à base de vinagre, azeite e mostarda.",
    prepTime: 15,
    cookTime: 20,
    servings: 6,
    category: "Zero Lactose",
    tags: ["Vegano", "Acompanhamento", "Salada", "Sem Glúten"],
    ingredients: [
        { value: "1kg de batatas pequenas, cozidas e fatiadas" },
        { value: "1/2 cebola roxa em fatias finas" },
        { value: "1/4 xícara de azeite de oliva" },
        { value: "3 colheres de sopa de vinagre de maçã" },
        { value: "1 colher de sopa de mostarda dijon" },
        { value: "1 colher de sopa de agave ou melado (opcional)" },
        { value: "Sal e pimenta do reino moída na hora" },
        { value: "Salsinha fresca picada a gosto" },
    ],
    instructions: [
        { value: "Cozinhe as batatas com casca em água e sal." },
        { value: "Em uma tigela grande, coloque as batatas fatiadas e a cebola roxa." },
        { value: "Em uma tigela pequena, prepare o molho." },
        { value: "Tempere o molho com sal e pimenta generosamente." },
        { value: "Regue as batatas com o molho enquanto elas ainda estiverem mornas." },
        { value: "Misture delicadamente e finalize com a salsinha picada." },
    ],
    substitutions: [
        "**Batata:** Qualquer batata que mantenha a forma depois de cozida funciona." ,
        "**Ervas:** Endro (dill) fresco picado é o tempero clássico para esta salada.",
    ],
    chefTip: "O segredo desta salada é temperá-la enquanto as batatas ainda estão mornas.",
  },
  'bolo-de-fuba-cremoso-sem-gluten': {
    title: "Bolo de Fubá Cremoso (Sem Glúten)",
    author: "Dona Cida",
    difficulty: "Fácil",
    description: "Este bolo de fubá tem uma textura única, com uma camada cremosa que se forma durante o cozimento. É mágico e delicioso! Perfeito para um café da tarde.",
    prepTime: 15,
    cookTime: 45,
    servings: 10,
    category: "Sem Glúten",
    tags: ["Sobremesa", "Bolo", "Zero Lactose"],
    ingredients: [
      { value: "4 ovos (claras e gemas separadas)" },
      { value: "2 xícaras de açúcar" },
      { value: "1 xícara de fubá mimoso" },
      { value: "3 colheres de sopa de amido de milho" },
      { value: "1/2 xícara de óleo de coco derretido" },
      { value: "4 xícaras de leite de coco" },
      { value: "1 colher de sopa de fermento em pó" },
      { value: "Erva-doce a gosto (opcional)" }
    ],
    instructions: [
      { value: "Pré-aqueça o forno a 180°C. Unte e enfarinhe (com fubá) uma forma." },
      { value: "No liquidificador, bata as gemas, o açúcar, o fubá, o amido, o óleo e o leite de coco até obter uma mistura homogênea." },
      { value: "Em uma batedeira, bata as claras em neve até ficarem bem firmes." },
      { value: "Incorpore delicadamente as claras em neve à mistura do liquidificador. Adicione o fermento e a erva-doce." },
      { value: "Despeje a massa (que é bem líquida) na forma e asse por cerca de 40-45 minutos, ou até dourar." },
      { value: "O bolo irá se separar em duas camadas. Deixe esfriar completamente para cortar." }
    ],
    substitutions: [
      "**Leite de coco:** Pode usar bebida de amêndoas, mas o de coco deixa mais cremoso.",
      "**Óleo de coco:** Pode ser substituído por outro óleo vegetal."
    ],
    chefTip: "Não se assuste com a massa líquida, é assim mesmo! A mágica acontece no forno. Espere esfriar completamente antes de desenformar para a camada cremosa firmar."
  },
  'pizza-com-massa-de-couve-flor': {
    title: "Pizza com Massa de Couve-Flor",
    author: "Ricardo Fitness",
    difficulty: "Médio",
    description: "Uma maneira incrível de comer pizza sem culpa e sem glúten! A massa fica surpreendentemente firme e deliciosa. Cubra com seus ingredientes favoritos.",
    prepTime: 20,
    cookTime: 30,
    servings: 2,
    category: "Sem Glúten",
    tags: ["Lanche", "Prato Principal", "Low Carb", "Zero Lactose"],
    ingredients: [
      { value: "1 cabeça de couve-flor média" },
      { value: "1 ovo (ou 1 'ovo' de linhaça)" },
      { value: "1/2 xícara de farinha de amêndoas" },
      { value: "1/4 xícara de levedura nutricional" },
      { value: "1 colher de chá de orégano seco" },
      { value: "Sal e pimenta a gosto" },
      { value: "Molho de tomate e toppings de sua preferência (cogumelos, azeitonas, etc)" }
    ],
    instructions: [
      { value: "Processe a couve-flor crua até virar uma 'farofa'. Cozinhe no micro-ondas por 4-5 minutos." },
      { value: "Deixe esfriar e coloque a couve-flor cozida em um pano de prato limpo. Torça bem para remover todo o excesso de água." },
      { value: "Em uma tigela, misture a couve-flor espremida com o ovo, farinha de amêndoas, levedura, orégano, sal e pimenta." },
      { value: "Abra a massa em formato de pizza sobre papel manteiga. Asse em forno a 220°C por 15-20 minutos, até dourar." },
      { value: "Retire do forno, espalhe o molho, os toppings e volte ao forno por mais 10 minutos." }
    ],
    substitutions: [
      "**Farinha de amêndoas:** Pode usar farinha de grão-de-bico ou de aveia sem glúten.",
      "**Ovo:** Para a versão vegana, use 1 colher de sopa de farinha de linhaça misturada com 3 colheres de sopa de água."
    ],
    chefTip: "O segredo para a massa não desmontar é espremer MUITO bem a couve-flor para tirar toda a água. Essa etapa é crucial!"
  },
  'beijinho-de-biomassa-de-banana-verde': {
    title: "Beijinho Funcional de Biomassa de Banana Verde",
    author: "Nutri Carol",
    difficulty: "Fácil",
    description: "Um docinho saudável, sem açúcar refinado e cheio de fibras! A biomassa de banana verde é a base neutra perfeita para criar um 'beijinho' cremoso e funcional.",
    prepTime: 10,
    cookTime: 5,
    servings: 15,
    category: "Sem Glúten",
    tags: ["Sobremesa", "Doce Rápido", "Vegano", "Zero Lactose"],
    ingredients: [
      { value: "1 xícara de biomassa de banana verde" },
      { value: "1/2 xícara de coco ralado seco sem açúcar" },
      { value: "1/4 xícara de leite de coco em pó" },
      { value: "3 colheres de sopa de xilitol (ou outro adoçante)" },
      { value: "2 colheres de sopa de óleo de coco" },
      { value: "Coco ralado para enrolar" },
      { value: "Cravos-da-índia para decorar" }
    ],
    instructions: [
      { value: "Em uma panela, misture todos os ingredientes, exceto o coco para enrolar." },
      { value: "Leve ao fogo baixo, mexendo constantemente, até a massa começar a desgrudar do fundo da panela (ponto de brigadeiro)." },
      { value: "Transfira a massa para um prato untado com óleo de coco e deixe esfriar completamente." },
      { value: "Com as mãos untadas, enrole os docinhos, passe no coco ralado e decore com um cravo." }
    ],
    substitutions: [
      "**Leite de coco em pó:** Aumente a quantidade de coco ralado se não tiver.",
      "**Xilitol:** Pode usar açúcar de coco ou melado, mas a cor do doce ficará mais escura."
    ],
    chefTip: "A biomassa de banana verde pode ser comprada pronta ou feita em casa, cozinhando bananas verdes na pressão e depois processando a polpa."
  }
};
    
    