[build]
  command = "next build"
  publish = ".next"

[functions]
  directory = "pages/api"
  included_files = ["src/lib/firebase-admin.ts", "src/lib/firebase.ts", ".env"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
